### ISSUE TITLE
Inefficient email checking on startup

### ISSUE THREAD

**Issue by JayDwee** [KoalaBotUK/KoalaBot#175]
### Describe the bug
The following message is printed to the console upon bot startup: 

user with id (`USER_ID`,) not found in `GUILD_NAME`

This bug/ current implementation also takes a long time to run by checking each email against each server where applicable. Instead only users within a server should be checked for if a verified email exists. Not the other way around (Checking for the user within a server for each valid email)

### To Reproduce
Numbered steps to reproduce the behavior:
1. Create 2 guilds
2. Have one user in one guild but not the other
3. Have that user verify with an email that matches both guild's verification settings

### Expected behaviour
No errors should be posted to the console. Any errors should use 'logging' library instead

### Screenshots
N/A due to privacy

### Contact Information (optional):
 - Version: 0.4.2 (latest)

### Additional context
N/A

**Comment by largereptile** [comment]
that particular bit to reproduce it isn't on startup, it's for adding verifications to a user. since we don't have a local way of checking if a user is in a specific server its probably better to just catch the error silently and move on rather than logging it though, you're right. I've reworked the one on startup to only attempt it on guild members though.

**Comment by JayDwee** [comment]
Just make sure it is as efficient as possible as we are frequently rate limited, and need to decrease the amount of requests sent to discord
